yarnPath: .yarn/releases/yarn-3.2.3.cjs
nodeLinker: node-modules
enableGlobalCache: true

packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      '@babel/plugin-syntax-flow': '^7'
      '@babel/plugin-transform-react-jsx': '^7'